import { NavLink } from "react-router-dom";
import { ModelStage } from "../features/experience/ModelStage";

export function About() {
  return <div className="studio-about">
    <header className="studio-page-heading studio-section"><p className="studio-eyebrow">THE STUDIO / INDEPENDENT BY DESIGN</p><h1>Good work<br />starts with care.</h1><p className="studio-page-lead">A clear idea. A thoughtful approach. Someone who cares about the details as much as you do.</p></header>
    <section className="studio-founder studio-section"><div><p className="studio-eyebrow">JAMES / FOUNDER & CEO</p><h2>The person<br /><span className="studio-soft">behind the pixels.</span></h2><p>I’m James, the founder of Crystal Powers. I design and develop websites, apps and bespoke digital systems for businesses and individuals who want something that feels their own.</p><p>Today, Crystal Powers is a one-person studio. You work directly with me from the first conversation through design, development and handover. That means a consistent point of contact and personal attention throughout your project.</p><NavLink to="/contact" className="studio-text-link">Let’s get acquainted ↗</NavLink></div><ModelStage model="crystal" className="studio-founder-art" title="Explore the studio signature" /></section>
    <section className="studio-introduction studio-section"><p className="studio-eyebrow">THE WAY I WORK</p><div><h2>Thought through.<br /><span className="studio-soft">From every angle.</span></h2><div className="studio-service-list">{[["01", "Your business comes first.", "We start with the people you serve, the work you do and what your project needs to achieve. The design follows that understanding."], ["02", "The details belong together.", "Content, layout, interaction and development are part of the same experience. I consider how they work together on every screen."], ["03", "Built for the next chapter.", "A project should be straightforward to use and maintain. I aim for a clear handover and a sensible path for changes after launch."]].map(([number, title, body]) => <article className="studio-service-row" key={number}><span className="studio-index">{number}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></div></section>
    <section className="studio-final studio-section"><p className="studio-eyebrow">LET’S BUILD SOMETHING THAT FITS</p><h2>Your idea.<br /><span>My full attention.</span></h2><NavLink to="/contact" className="studio-button">Tell me what you’re thinking ↗</NavLink></section>
  </div>;
}
