-- Legacy examples are PRIVATE DRAFTS. A cover image and owner review are required before publication.
INSERT INTO project (id, slug) VALUES ('ed118fad-d178-d6f0-448f-e1d3444e756c', 'editorial-service-landing-flow');
INSERT INTO project_revision (id, project_id, version, payload) VALUES ('21e7100b-cac0-f12a-ac36-865a482986f1', 'ed118fad-d178-d6f0-448f-e1d3444e756c', 1, '{"title":"Editorial service landing flow","category":"WEBSITE","summary":"Premium website direction focused on tone, hierarchy, and a cleaner path from first impression to enquiry.","overview":"The build was structured to feel premium immediately: editorial pacing, generous spacing, and a cleaner hierarchy around the service offer.","approach":"I built this around a cleaner page rhythm, bolder typography, and sections that guide the eye instead of competing for attention.","outcome":"What makes it work is the way the page feels intentional from top to bottom. The layout does not just look polished; it supports the offer and makes the client feel more established.","liveUrl":"","technologies":[],"displayDevice":"laptop","coverMediaId":null,"coverAlt":"","gallery":[]}');
INSERT INTO project (id, slug) VALUES ('408f0df4-ca40-ea97-0450-688e82650960', 'product-detail-conversion-pass');
INSERT INTO project_revision (id, project_id, version, payload) VALUES ('a5c0b5c6-9d4c-6ab1-1dcc-b65c3e5fdd79', '408f0df4-ca40-ea97-0450-688e82650960', 1, '{"title":"Product detail and conversion pass","category":"WEBSITE","summary":"Storefront layout shaped to make the product clearer, the offer sharper, and the conversion path easier to trust.","overview":"This project focused on product hierarchy and a stronger buying journey, keeping the design cleaner while making the product value more legible.","approach":"The work was built around simplifying the storefront: tightening component spacing, clarifying section order, and pushing important actions higher in the visual flow.","outcome":"The result works because it feels easier to scan and easier to trust. The page stops feeling crowded and starts behaving like a proper conversion surface.","liveUrl":"","technologies":[],"displayDevice":"laptop","coverMediaId":null,"coverAlt":"","gallery":[]}');
INSERT INTO project (id, slug) VALUES ('a0d8c14a-8857-39cd-8abd-52ef3c2cf95c', 'portfolio-booking-surface');
INSERT INTO project_revision (id, project_id, version, payload) VALUES ('469e37ef-b8fb-2ab2-339f-742cc2533d86', 'a0d8c14a-8857-39cd-8abd-52ef3c2cf95c', 1, '{"title":"Portfolio and booking surface","category":"WEBSITE","summary":"Booking-ready portfolio designed to let the work lead while keeping the presentation clean, sharp, and premium.","overview":"This build balanced personality with restraint, letting the portfolio feel premium without drowning the work in unnecessary decoration.","approach":"I built it around a lighter structure with stronger spacing, clearer image framing, and a simpler route into contact or booking.","outcome":"It works because the work stays central. The interface supports the creator instead of stealing attention from what they have actually made.","liveUrl":"","technologies":[],"displayDevice":"laptop","coverMediaId":null,"coverAlt":"","gallery":[]}');
INSERT INTO project (id, slug) VALUES ('552a8866-a671-9e72-4f84-b6728f1be8c9', 'launch-support-surface');
INSERT INTO project_revision (id, project_id, version, payload) VALUES ('8ec220a0-6a77-8225-0d2e-97d00fe59f93', '552a8866-a671-9e72-4f84-b6728f1be8c9', 1, '{"title":"Launch support surface","category":"WEBSITE","summary":"Sharper launch-facing page built to frame an offer, hold attention, and keep the rollout visually consistent.","overview":"This build focused on launch presentation, pairing bolder visual treatment with a tighter page structure so the offer felt more elevated.","approach":"The page was shaped around the campaign story first, then tightened into a stronger rhythm with fewer competing elements.","outcome":"It works because the visuals support the message instead of overshadowing it. The page feels like part of the launch, not an afterthought around it.","liveUrl":"","technologies":[],"displayDevice":"laptop","coverMediaId":null,"coverAlt":"","gallery":[]}');
INSERT INTO project (id, slug) VALUES ('189feb37-d12a-393b-1e51-94b4c9d4984d', 'operational-structure-showcase');
INSERT INTO project_revision (id, project_id, version, payload) VALUES ('494751e0-55a4-4a53-b96e-0a441858b6f9', '189feb37-d12a-393b-1e51-94b4c9d4984d', 1, '{"title":"Operational structure showcase","category":"SYSTEM","summary":"Project view focused on making systems, structure, and operational clarity feel more visible and professional.","overview":"This project translated a structural service into something easier to understand visually, using cleaner blocks and stronger hierarchy.","approach":"The focus was on simplifying how the structure was presented, so the page felt more confident without losing technical clarity.","outcome":"It works because the project feels easier to trust. The page communicates system depth without forcing the user to work to understand it.","liveUrl":"","technologies":[],"displayDevice":"laptop","coverMediaId":null,"coverAlt":"","gallery":[]}');
INSERT INTO project (id, slug) VALUES ('c4e38c18-f361-53ce-e3cc-41176793a8d0', 'automation-workflow-preview');
INSERT INTO project_revision (id, project_id, version, payload) VALUES ('9ab29093-0e97-66c8-4090-b02ed789947b', 'c4e38c18-f361-53ce-e3cc-41176793a8d0', 1, '{"title":"Automation workflow preview","category":"SYSTEM","summary":"Scoped automation concept framed as part of a wider digital system rather than a disconnected utility page.","overview":"This project focused on presenting a smaller automation system in a way that still felt polished, premium, and integrated into the client offer.","approach":"I approached it by tightening the structure around the workflow story: what it does, how it helps, and why the scope stays intentionally controlled.","outcome":"It works because the automation feels purposeful instead of gimmicky. The page explains the value while still fitting a more premium studio style.","liveUrl":"","technologies":[],"displayDevice":"laptop","coverMediaId":null,"coverAlt":"","gallery":[]}');
